micronaut:
    application:
        name: veganscan-api

mongodb:
    uri: mongodb://api_test_user:nasf983wfnw3finoesinc@ds139167.mlab.com:39167

vegandb:
    database:
        name: heroku_sfl14q82

