micronaut:
    application:
        name: veganscan-api
    server:
        port: 8087

mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

vegandb:
    database:
        name: vegandb
