micronaut:
    application:
        name: veganscan-api

mongodb:
    uri: mongodb://$DATABASE_USER:$DATABASE_PASSWORD@ds139167.mlab.com:39167/heroku_sfl14q82

vegandb:
    database:
        name: heroku_sfl14q82

#nasf983wfnw3finoesinc
