micronaut:
    application:
        name: veganscan-api

mongodb:
    uri: mongodb://heroku_sfl14q82:testpassword1@ds139167.mlab.com:39167/heroku_sfl14q82

vegandb:
    database:
        name: heroku_sfl14q82

